#
# Copyright (c) 2012-2017 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

{{- if and .Values.global.tls }}
{{- if and .Values.global.tls.enabled .Values.global.tls.useCertManager }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # The ACME server URL
{{- if .Values.global.tls.useStaging }}
    server: https://acme-staging.api.letsencrypt.org/directory
{{- else }}
    server: https://acme-v01.api.letsencrypt.org/directory
{{- end }}
    # Email address used for ACME registration
    email: user@example.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt
    # Enable the HTTP-01 challenge provider
    http01: {}
{{- end }}
{{- end }}