#
# Copyright (c) 2012-2017 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

{{- if (.Values.global.cheWorkspacesNamespace) }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: exec
  namespace: {{ .Values.global.cheWorkspacesNamespace }}
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
    - pods/exec
  verbs:
    - create
{{- end }}
