#
# Copyright (c) 2012-2017 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: che-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/proxy-read-timeout: "3600"
    {{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/proxy-connect-timeout: "3600"
{{- if and .Values.global.tls .Values.global.tls.enabled }}
    {{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/ssl-redirect: "true"
{{- else }}
    {{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/ssl-redirect: "false"
{{- end }}
{{- if and .Values.global.tls .Values.global.tls.enabled .Values.global.tls.useCertManager }}
    certmanager.k8s.io/cluster-issuer: "letsencrypt"
{{- end }}
spec:
{{- if .Values.global.tls.enabled }}
  tls:
  - hosts:
    - {{ template "cheHost" . }}
    secretName: {{ .Values.global.tls.secretName }}
{{- end }}
  rules:
{{- if ne .Values.global.serverStrategy "default-host" }}
  - host: {{ template "cheHost" . }}
    http:
{{- else }}
  - http:
{{- end }}
      paths:
      - path: /
        backend:
          serviceName: che-host
          servicePort: 8080
