---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ca-cert-generator-role-binding
  namespace: cert-manager
subjects:
- kind: ServiceAccount
  name: ca-cert-generator
  apiGroup: ''
roleRef:
  kind: Role
  name: ca-cert-generator-role
  apiGroup: ''
