---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ca-cert-generator-role
  namespace: cert-manager
rules:
- apiGroups:
    - ''
  resources:
    - secrets
  verbs:
    - create
