kind: ConfigMap
apiVersion: v1
metadata:
  name: dex
  namespace: dex
  labels:
    app: dex
data:
  config.yaml: |
    issuer: https://dex.{{DOMAIN}}
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556

    oauth2:
      skipApprovalScreen: true

    staticClients:
    - id: {{CLIENT_ID}}
      redirectURIs:
      - 'https://{{DOMAIN}}/oauth/callback'
      name: 'Eclipse Che'
      secret: {{CLIENT_SECRET}}
    enablePasswordDB: true
    staticPasswords:
    - email: "che@eclipse.org"
      hash: "{{DEX_PASSWORD_HASH}}"
      username: "admin"
      userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
    - email: "user1@che"
      hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
      username: "user1"
      userID: "1"
    - email: "user2@che"
      hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
      username: "user2"
      userID: "2"
    - email: "user3@che"
      hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
      username: "user3"
      userID: "3"
    - email: "user4@che"
      hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
      username: "user4"
      userID: "4"
    - email: "user5@che"
      hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
      username: "user5"
      userID: "5"
