#
# Copyright (c) 2019-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

name: Code Coverage Report
on: [push]
jobs:
  code-coverage-report:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 16.13.2
      - name: Build chectl
        run: yarn
      - name: Install codecov
        run: npm install codecov -g
      - name: Run unit tests
        run: yarn test
      - name: Submit code coverage results
        run: bash <(curl -s https://codecov.io/bash)
