#
# Copyright (c) 2019-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

name: Happy Path
on:
  pull_request:
    branches:
      - '7.*.x'
jobs:
  happy-path:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Start minikube cluster
        uses: che-incubator/setup-minikube-action@next
        with:
          minikube-version: v1.23.2
      - name: Install NodeJS
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16.13.2
      - name: Build chectl
        run: yarn
      - name: Add chectl to $PATH
        run: |
          ln -s $(pwd)/bin/run $(pwd)/bin/chectl
          echo "$PWD/bin" >> $GITHUB_PATH
      - name: Deploy Eclipse Che
        uses: che-incubator/che-deploy-action@next
        with:
          # use custom chectl built by this PR
          skip-chectl-install: true
      - name: Run Happy Path tests
        uses: che-incubator/happy-path-tests-action@next
        with:
          che-url: ${{ steps.deploy-che.outputs.che-url }}
      - name: Collect Eclipse Che logs
        if: ${{ always() }}
        run: chectl server:logs -d che/tests/e2e/report
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-artifacts
          path: che/tests/e2e/report
