#
# Copyright (c) 2019-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

name: Commands tests
on: pull_request
jobs:
  chectl-deploy-commands:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Start minikube cluster
      uses: che-incubator/setup-minikube-action@next
      with:
        minikube-version: v1.23.2
    - name: Install NodeJS
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 16.13.2
    - name: Build chectl
      run: yarn
    - name: Run e2e tests
      run: |
        export PLATFORM=minikube
        export INSTALLER=operator
        yarn test --coverage=false --forceExit --testRegex=test/e2e/e2e.test.ts
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: test-artifacts
        path: /tmp/logs/*
  chectl-update-commands:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Start minikube cluster
      uses: che-incubator/setup-minikube-action@next
      with:
        minikube-version: v1.23.2
    - name: Install chectl from the stable channel
      run: bash <(curl -sL  https://www.eclipse.org/che/chectl/) --channel=stable
    - name: Install NodeJS
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 16.13.2
    - name: Build chectl
      run: yarn
    - name: Run tests
      run: |
        export PLATFORM=minikube
        export INSTALLER=operator
        yarn test --coverage=false --forceExit --testRegex=test/e2e/e2e-upgrade.test.ts
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: test-artifacts
        path: /tmp/logs/*
