#
# Copyright (c) 2019-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

name: Minikube DevWorkspace
on: pull_request
jobs:
  needs: [unit-tests, license, readme.md]
  minikube-devworkspace:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Start minikube cluster
      id: run-minikube
      uses: che-incubator/setup-minikube-action@next
      with:
        minikube-version: v1.23.2
    - name: Build chectl
      run: yarn
    - name: Deploy Eclipse Che with DevWorkspace engine enabled
      run: ./bin/run server:deploy --telemetry=off --workspace-engine=dev-workspace -p minikube --batch
