name: Chectl
on: [pull_request]

jobs:
  run:
    name: Automation checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Pack chectl
        run: yarn pack
      - name: Check README.md state
        run: |
          IFS=$'\n' read -d '' -r -a FILES_CHANGED_ARRAY < <( git ls-files -m ) || true
          # check if readme it is updated
          if [[ " ${FILES_CHANGED_ARRAY[@]} " =~ "README.md" ]]; then
            echo "[ERROR] README.md it is not updated. Please run yarn pack to update and commit the changes."
            exit 1
          fi

