#
#  Copyright (c) 2021 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
name: Release - send mattermost notification
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version that is going to be announced. Should be in format 7.y.z'
        required: true
  push:
    # on change to VERSION file only (PR merged as part of release)
    paths:
      - 'VERSION'
    # Trigger on push only for 7.y.* branch
    branches:
      - '7.*.*'
jobs:
  notify:
    runs-on: ubuntu-20.04
    steps:
      - name: Create MM message
        run: |
          if [[ ${{ github.event.inputs.version }} != "" ]]; then
            version=${{ github.event.inputs.version }}
            milestone=${version%.*}; echo "version milestone: ${milestone}"
          else
            version=$(cat VERSION)
            milestone=${version%.*}; echo "branch milestone: ${milestone}"
          fi
          echo "{\"text\":\":building_construction: chectl ${version} has been released: https://github.com/che-incubator/chectl/releases/tag/${version}\n\nPlease resolve or move unresolved issues assigned to this milestone: https://github.com/eclipse/che/milestones/${milestone}\"}" > mattermost.json
      - name: Send MM message
        uses: mattermost/action-mattermost-notify@1.0.2
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_CHANNEL: eclipse-che-releases
          MATTERMOST_USERNAME: che-bot
